### ISSUE TITLE
Handle errors and produce good error messages

### ISSUE THREAD

**Issue by casey** [soenkehahn/foo#20]
I usually use [snafu](https://docs.rs/snafu/0.6.10/snafu/index.html) for error handling. It's not as convenient as [anyhow](https://docs.rs/anyhow/1.0.40/anyhow/), which allows returning arbitrary errors with arbitrary chains of causes, but it makes testing easier, because you can check that specific errors are returned, and forces you to be explicit about causal chains.

We could also consider using [fehler](https://github.com/withoutboats/fehler)  which slightly reduces boilerplate.

**Comment by soenkehahn** [comment]
We switched to `anyhow` in #19. We're going to defer switching to anything fancier for now.
